const vscode = require("vscode");
const fs = require("fs");
const path = require("path");
const { createRequire } = require("module");
const { pathToFileURL } = require("url");

const SELECTOR = [
  { scheme: "file", language: "idsl", pattern: "**/*.idsl" },
  { scheme: "file", language: "idsl", pattern: "**/*.dsljs" },
  { scheme: "file", language: "javascript", pattern: "**/*.idsl" },
  { scheme: "file", language: "javascript", pattern: "**/*.dsljs" }
];

const TOKEN_TYPES = ["keyword", "function", "variable", "class", "parameter"];
const TOKEN_MODIFIERS = ["declaration"];
const legend = new vscode.SemanticTokensLegend(TOKEN_TYPES, TOKEN_MODIFIERS);
const macroNameDecoration = vscode.window.createTextEditorDecorationType({
  color: new vscode.ThemeColor("symbolIcon.functionForeground"),
  fontWeight: "bold"
});
const templateInterpolationDecoration = vscode.window.createTextEditorDecorationType({
  color: new vscode.ThemeColor("symbolIcon.variableForeground"),
  fontWeight: "bold"
});

function isDslDocument(document) {
  const file = document.uri.fsPath;
  return file.endsWith(".dsljs") || file.endsWith(".idsl");
}

function getShadowOutputPath(inputFile) {
  if (inputFile.endsWith(".idsl")) {
    return inputFile.slice(0, -".idsl".length) + ".generated.js";
  }

  if (inputFile.endsWith(".dsljs")) {
    return inputFile.slice(0, -".dsljs".length) + ".generated.js";
  }

  return `${inputFile}.generated.js`;
}

function buildShadowFileContents(inputFile, expanded) {
  const normalizedInput = inputFile.replace(/\\/g, "/");
  return [
    "// @ts-check",
    `// Generated from: ${normalizedInput}`,
    "// Do not edit this file directly.",
    "",
    expanded.trim(),
    ""
  ].join("\n");
}

const PACKAGE_CANDIDATES = ["dsljs", "idsljs", "idsljs-macros"];

function findProjectRoot(startPath) {
  const resolvedStartPath = path.resolve(startPath);
  const stat = fs.existsSync(resolvedStartPath) ? fs.statSync(resolvedStartPath) : null;
  let currentDir = stat?.isDirectory()
    ? resolvedStartPath
    : path.dirname(resolvedStartPath);

  while (true) {
    const parserPath = path.join(currentDir, "src", "parser.js");
    const packageJsonPath = path.join(currentDir, "package.json");
    if (fs.existsSync(parserPath) && fs.existsSync(packageJsonPath)) {
      return currentDir;
    }

    const parentDir = path.dirname(currentDir);
    if (parentDir === currentDir) break;
    currentDir = parentDir;
  }

  for (const folder of vscode.workspace.workspaceFolders ?? []) {
    const parserPath = path.join(folder.uri.fsPath, "src", "parser.js");
    const packageJsonPath = path.join(folder.uri.fsPath, "package.json");
    if (fs.existsSync(parserPath) && fs.existsSync(packageJsonPath)) {
      return folder.uri.fsPath;
    }
  }

  throw new Error("Could not find src/parser.js in the current workspace.");
}

function findNearestPackageRoot(startPath) {
  const resolvedStartPath = path.resolve(startPath);
  const stat = fs.existsSync(resolvedStartPath) ? fs.statSync(resolvedStartPath) : null;
  let currentDir = stat?.isDirectory()
    ? resolvedStartPath
    : path.dirname(resolvedStartPath);

  while (true) {
    const packageJsonPath = path.join(currentDir, "package.json");
    if (fs.existsSync(packageJsonPath)) {
      return currentDir;
    }

    const parentDir = path.dirname(currentDir);
    if (parentDir === currentDir) break;
    currentDir = parentDir;
  }

  const workspaceFolder = vscode.workspace.getWorkspaceFolder(vscode.Uri.file(resolvedStartPath));
  if (workspaceFolder) {
    return workspaceFolder.uri.fsPath;
  }

  for (const folder of vscode.workspace.workspaceFolders ?? []) {
    return folder.uri.fsPath;
  }

  return __dirname;
}

function tryResolvePackageParserPath(startPath) {
  const packageRoot = findNearestPackageRoot(startPath);
  const resolver = createRequire(path.join(packageRoot, "package.json"));

  for (const packageName of PACKAGE_CANDIDATES) {
    try {
      return resolver.resolve(packageName);
    } catch {}
  }

  return null;
}

function getParserPath(startPath) {
  try {
    return path.join(findProjectRoot(startPath), "src", "parser.js");
  } catch {}

  const resolvedPackagePath = tryResolvePackageParserPath(startPath);
  if (resolvedPackagePath) {
    return resolvedPackagePath;
  }

  throw new Error("Could not find src/parser.js or resolve the dsljs package from the current file.");
}

async function loadParser(startPath) {
  const parserPath = getParserPath(startPath);
  const parserUrl = pathToFileURL(parserPath).href;
  return import(parserUrl);
}

function getWorkspaceRoot(startPath) {
  return findNearestPackageRoot(startPath);
}

function getWorkspaceRequire(startPath) {
  const workspaceRoot = getWorkspaceRoot(startPath);
  return createRequire(path.join(workspaceRoot, "package.json"));
}

function loadWorkspaceEslint(startPath) {
  try {
    const workspaceRequire = getWorkspaceRequire(startPath);
    return workspaceRequire("eslint");
  } catch {}

  const parserPath = getParserPath(startPath);
  const parserRequire = createRequire(parserPath);
  return parserRequire("eslint");
}

async function compileSource(text, sourcePath) {
  const parser = await loadParser(sourcePath);
  return parser.compileDslSource(text, { sourcePath });
}

async function compileFile(inputFile) {
  const parser = await loadParser(inputFile);
  return parser.compileDslFile(inputFile);
}

async function syncShadowForFile(inputFile) {
  const expanded = await compileFile(inputFile);
  const shadowPath = getShadowOutputPath(inputFile);
  const contents = buildShadowFileContents(inputFile, expanded);
  fs.writeFileSync(shadowPath, contents, "utf8");
  return shadowPath;
}

function offsetToPosition(text, offset) {
  const prefix = text.slice(0, offset);
  const lines = prefix.split(/\r?\n/u);
  const line = lines.length - 1;
  const character = lines[lines.length - 1].length;
  return new vscode.Position(line, character);
}

function addMatchDefinition(defs, text, regex, groupIndex) {
  let match;
  while ((match = regex.exec(text)) !== null) {
    const name = match[groupIndex];
    if (!name || defs.has(name)) continue;

    const nameOffset = match.index + match[0].lastIndexOf(name);
    const start = offsetToPosition(text, nameOffset);
    const end = start.translate(0, name.length);
    defs.set(name, new vscode.Location(vscode.Uri.file(""), new vscode.Range(start, end)));
  }
}

function collectDefinitions(document) {
  const text = document.getText();
  const defs = new Map();

  addMatchDefinition(
    defs,
    text,
    /(?:^|[\r\n]\s*)(?:const|let|var|function|class)\s+([A-Za-z_$\p{L}][A-Za-z0-9_$\p{L}]*)/gmu,
    1
  );
  addMatchDefinition(
    defs,
    text,
    /(?:^|[\r\n]\s*)THREE\s+([A-Za-z_$\p{L}][A-Za-z0-9_$\p{L}]*)\s*\.\s*([A-Za-z_$\p{L}][A-Za-z0-9_$\p{L}]*)/gmu,
    1
  );
  addMatchDefinition(
    defs,
    text,
    /(?:^|[\r\n]\s*)struct\s+([A-Za-z_$\p{L}][A-Za-z0-9_$\p{L}]*)\s*\[/gmu,
    1
  );

  for (const [name, location] of defs) {
    defs.set(name, new vscode.Location(document.uri, location.range));
  }

  return defs;
}

function collectMacroDefinitions(document) {
  return collectMacroDefinitionsFromFile(document.uri.fsPath);
}

function getDslSymbolAtPosition(document, position) {
  const line = document.lineAt(position.line).text;
  const char = line[position.character] ?? "";
  const prev = position.character > 0 ? line[position.character - 1] : "";

  if ((char === "[" && line[position.character + 1] === ">") || (char === ">" && prev === "[")) {
    const start = char === "[" ? position.character : position.character - 1;
    const range = new vscode.Range(
      new vscode.Position(position.line, start),
      new vscode.Position(position.line, start + 2)
    );
    return { symbol: "[>", range };
  }

  const range = document.getWordRangeAtPosition(position, /[A-Za-z_$\p{L}][A-Za-z0-9_$\p{L}]*/u);
  if (!range) return null;

  return {
    symbol: document.getText(range),
    range
  };
}

function extractMacroImports(source) {
  const imports = [];
  const importRe =
    /^\s*import\s+macros(?:\s+from)?\s+["']([^"']+)["']\s*;?\s*$/gmu;

  let match;
  while ((match = importRe.exec(source)) !== null) {
    imports.push(match[1]);
  }

  return imports;
}

function resolveMacroImport(specifier, sourcePath) {
  return path.resolve(path.dirname(sourcePath), specifier);
}

function collectMacroDefinitionsFromFile(filePath, seen = new Set()) {
  const resolvedPath = path.resolve(filePath);
  if (seen.has(resolvedPath) || !fs.existsSync(resolvedPath)) {
    return new Map();
  }

  seen.add(resolvedPath);
  const text = fs.readFileSync(resolvedPath, "utf8");
  const defs = new Map();

  addMatchDefinition(
    defs,
    text,
    /(?:^|[\r\n]\s*)\$macro\s+([A-Za-z_$\p{L}\[\]>][A-Za-z0-9_$\p{L}\[\]>-]*)/gmu,
    1
  );

  for (const [name, location] of defs) {
    defs.set(name, new vscode.Location(vscode.Uri.file(resolvedPath), location.range));
  }

  for (const specifier of extractMacroImports(text)) {
    const importedPath = resolveMacroImport(specifier, resolvedPath);
    const importedDefs = collectMacroDefinitionsFromFile(importedPath, seen);
    for (const [name, location] of importedDefs) {
      if (!defs.has(name)) {
        defs.set(name, location);
      }
    }
  }

  return defs;
}

function findGeneratedSnippet(expanded, symbol) {
  const lines = expanded.split(/\r?\n/u);
  const patterns = [
    new RegExp(`\\bconst\\s+${symbol}\\b`),
    new RegExp(`\\blet\\s+${symbol}\\b`),
    new RegExp(`\\bvar\\s+${symbol}\\b`),
    new RegExp(`\\bfunction\\s+${symbol}\\b`),
    new RegExp(`\\bclass\\s+${symbol}\\b`)
  ];

  const index = lines.findIndex(line => patterns.some(pattern => pattern.test(line)));
  if (index === -1) return null;

  return lines.slice(index, Math.min(index + 4, lines.length)).join("\n").trim();
}

function escapeRegexLiteral(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function countSymbolOccurrencesBefore(text, symbol, offset) {
  const symbolRe = new RegExp(`\\b${escapeRegexLiteral(symbol)}\\b`, "gu");
  let count = 0;

  for (const match of text.matchAll(symbolRe)) {
    if ((match.index ?? 0) > offset) break;
    count++;
  }

  return Math.max(1, count);
}

function findSymbolPositionByOrdinal(text, symbol, ordinal) {
  const symbolRe = new RegExp(`\\b${escapeRegexLiteral(symbol)}\\b`, "gu");
  let count = 0;

  for (const match of text.matchAll(symbolRe)) {
    count++;
    if (count === ordinal) {
      return offsetToPosition(text, match.index ?? 0);
    }
  }

  return null;
}

async function resolveShadowSymbolPosition(document, position, symbol) {
  try {
    await syncShadowForFile(document.uri.fsPath);
  } catch {
    return null;
  }

  const shadowPath = getShadowOutputPath(document.uri.fsPath);
  if (!fs.existsSync(shadowPath)) return null;

  const shadowDocument = await vscode.workspace.openTextDocument(shadowPath);
  const sourceOffset = document.offsetAt(position);
  const ordinal = countSymbolOccurrencesBefore(document.getText(), symbol, sourceOffset);
  const shadowPosition =
    findSymbolPositionByOrdinal(shadowDocument.getText(), symbol, ordinal) ??
    findSymbolPositionByOrdinal(shadowDocument.getText(), symbol, 1);

  if (!shadowPosition) return null;

  return { shadowDocument, shadowPosition };
}

async function provideGeneratedDefinition(document, position, symbol) {
  const resolved = await resolveShadowSymbolPosition(document, position, symbol);
  if (!resolved) return null;

  const result = await vscode.commands.executeCommand(
    "vscode.executeDefinitionProvider",
    resolved.shadowDocument.uri,
    resolved.shadowPosition
  );

  return result?.length ? result : null;
}

async function provideGeneratedHover(document, position, symbol) {
  const resolved = await resolveShadowSymbolPosition(document, position, symbol);
  if (!resolved) return null;

  const result = await vscode.commands.executeCommand(
    "vscode.executeHoverProvider",
    resolved.shadowDocument.uri,
    resolved.shadowPosition
  );

  return result?.length ? result[0] : null;
}

function tokenTypeIndex(name) {
  return TOKEN_TYPES.indexOf(name);
}

function tokenModifierMask(name) {
  const index = TOKEN_MODIFIERS.indexOf(name);
  return index === -1 ? 0 : (1 << index);
}

function addToken(builder, line, start, length, type, modifier) {
  if (length <= 0) return;
  builder.push(line, start, length, tokenTypeIndex(type), tokenModifierMask(modifier));
}

function collectGeneratedDeclarationNames(expanded) {
  const names = new Set();
  const declarationRe =
    /\b(?:const|let|var|function|class)\s+([A-Za-z_$\p{L}][A-Za-z0-9_$\p{L}]*)/gu;

  for (const match of expanded.matchAll(declarationRe)) {
    names.add(match[1]);
  }

  return names;
}

function collectMacroHeads(document) {
  const heads = new Set();
  const text = document.getText();

  for (const match of text.matchAll(/^\s*\$macro\s+([A-Za-z_$\p{L}][A-Za-z0-9_$\p{L}]*)/gmu)) {
    heads.add(match[1]);
  }

  return heads;
}

async function provideSemanticTokens(document) {
  const builder = new vscode.SemanticTokensBuilder(legend);
  const lines = document.getText().split(/\r?\n/u);
  const macroDefinitions = collectMacroDefinitions(document);
  const macroHeads = new Set(macroDefinitions.keys());
  const jsGlobals = new Set([
    "document",
    "console",
    "window",
    "globalThis",
    "Math",
    "JSON",
    "Object",
    "Array",
    "String",
    "Number",
    "Boolean",
    "Promise",
    "Set",
    "Map",
    "Date"
  ]);
  let generatedDeclarationNames = new Set();

  try {
    const expanded = await compileSource(document.getText(), document.uri.fsPath);
    generatedDeclarationNames = collectGeneratedDeclarationNames(expanded);
  } catch {}

  for (let lineNumber = 0; lineNumber < lines.length; lineNumber++) {
    const line = lines[lineNumber];

    for (const keywordMatch of line.matchAll(/\b(import|let|const|var|return|export|from)\b/gu)) {
      const keyword = keywordMatch[1];
      addToken(builder, lineNumber, keywordMatch.index ?? 0, keyword.length, "keyword");
    }

    let match = line.match(/^(\s*)\$macro\s+(\[>|[A-Za-z_$\p{L}][A-Za-z0-9_$\p{L}]*)/u);
    if (match) {
      addToken(builder, lineNumber, match[1].length, "$macro".length, "keyword");
      addToken(builder, lineNumber, match[1].length + "$macro ".length, match[2].length, "function", "declaration");
    }

    match = line.match(/^(\s*)THREE\s+([A-Za-z_$\p{L}][A-Za-z0-9_$\p{L}]*)\s*\.\s*([A-Za-z_$\p{L}][A-Za-z0-9_$\p{L}]*)/u);
    if (match) {
      addToken(builder, lineNumber, match[1].length, "THREE".length, "function");
      addToken(builder, lineNumber, line.indexOf(match[2]), match[2].length, "variable", "declaration");
      addToken(builder, lineNumber, line.lastIndexOf(match[3]), match[3].length, "class");
    }

    match = line.match(/^(\s*)struct\s+([A-Za-z_$\p{L}][A-Za-z0-9_$\p{L}]*)/u);
    if (match) {
      addToken(builder, lineNumber, match[1].length, "struct".length, "keyword");
      addToken(builder, lineNumber, line.indexOf(match[2]), match[2].length, "class", "declaration");
    }

    match = line.match(/^(\s*)([A-Za-z_$\p{L}][A-Za-z0-9_$\p{L}]*)\s*\(/u);
    if (match && generatedDeclarationNames.has(match[2])) {
      addToken(builder, lineNumber, match[1].length, match[2].length, "variable", "declaration");
    }

    for (const globalMatch of line.matchAll(/\b([A-Za-z_$\p{L}][A-Za-z0-9_$\p{L}]*)\b/gu)) {
      const name = globalMatch[1];
      if (!jsGlobals.has(name)) continue;
      addToken(builder, lineNumber, globalMatch.index ?? 0, name.length, "variable");
    }

    for (const memberCallMatch of line.matchAll(/\.\s*([A-Za-z_$\p{L}][A-Za-z0-9_$\p{L}]*)\s*(?=\()/gu)) {
      const name = memberCallMatch[1];
      const start = (memberCallMatch.index ?? 0) + memberCallMatch[0].lastIndexOf(name);
      addToken(builder, lineNumber, start, name.length, "function");
    }

    for (const bareCallMatch of line.matchAll(/\b([A-Za-z_$\p{L}][A-Za-z0-9_$\p{L}]*)\s*(?=\()/gu)) {
      const name = bareCallMatch[1];
      if (macroHeads.has(name) || generatedDeclarationNames.has(name) || jsGlobals.has(name)) continue;
      const start = bareCallMatch.index ?? 0;
      const prevChar = start > 0 ? line[start - 1] : "";
      if (prevChar === "." || prevChar === "$") continue;
      addToken(builder, lineNumber, start, name.length, "function");
    }

    for (const head of macroHeads) {
      if (head === "[>") {
        for (const headMatch of line.matchAll(/\[>/gu)) {
          const start = headMatch.index ?? 0;
          addToken(builder, lineNumber, start, 2, "keyword");
        }
        continue;
      }

      const headRe = new RegExp(`\\b${head}\\b`, "gu");
      for (const headMatch of line.matchAll(headRe)) {
        const start = headMatch.index ?? 0;
        const linePrefix = line.slice(0, start);
        const isMacroDefinition = /^\s*\$macro\s+$/u.test(linePrefix);
        if (isMacroDefinition) continue;
        addToken(builder, lineNumber, start, head.length, "keyword");
      }
    }

    for (const ph of line.matchAll(/\$([A-Za-z_$\p{L}][A-Za-z0-9_$\p{L}]*)/gu)) {
      const start = ph.index ?? 0;
      addToken(builder, lineNumber, start, ph[0].length, "parameter");
    }
  }

  return builder.build();
}

function debounce(fn, waitMs) {
  let timer = null;
  return (...args) => {
    if (timer) clearTimeout(timer);
    timer = setTimeout(() => {
      timer = null;
      fn(...args);
    }, waitMs);
  };
}

function collectMacroDefinitionRanges(document) {
  const ranges = [];
  const lines = document.getText().split(/\r?\n/u);

  for (let lineNumber = 0; lineNumber < lines.length; lineNumber++) {
    const line = lines[lineNumber];
    const match = line.match(/^(\s*)\$macro\s+([A-Za-z_$\p{L}][A-Za-z0-9_$\p{L}]*)/u);
    if (!match) continue;

    const start = line.indexOf(match[2]);
    const range = new vscode.Range(
      new vscode.Position(lineNumber, start),
      new vscode.Position(lineNumber, start + match[2].length)
    );
    ranges.push(range);
  }

  return ranges;
}

function collectTemplateDecorations(document) {
  const text = document.getText();
  const interpolationRanges = [];

  let i = 0;
  while (i < text.length) {
    if (text[i] !== "`" || text[i - 1] === "\\") {
      i++;
      continue;
    }

    const templateStart = i;
    i++;

    while (i < text.length) {
      if (text[i] === "\\" && i + 1 < text.length) {
        i += 2;
        continue;
      }

      if (text[i] === "$" && text[i + 1] === "{") {
        const interpStart = i;
        i += 2;
        let depth = 1;

        while (i < text.length && depth > 0) {
          if (text[i] === "\\" && i + 1 < text.length) {
            i += 2;
            continue;
          }

          if (text[i] === "{") depth++;
          else if (text[i] === "}") depth--;
          i++;
        }

        interpolationRanges.push(new vscode.Range(
          offsetToPosition(text, interpStart),
          offsetToPosition(text, interpStart + 2)
        ));

        interpolationRanges.push(new vscode.Range(
          offsetToPosition(text, i - 1),
          offsetToPosition(text, i)
        ));
        continue;
      }

      if (text[i] === "`") {
        i++;
        break;
      }

      i++;
    }
  }

  return { interpolationRanges };
}

function refreshDecorations(editor) {
  if (!editor || !isDslDocument(editor.document)) return;
  editor.setDecorations(macroNameDecoration, collectMacroDefinitionRanges(editor.document));

  const { interpolationRanges } = collectTemplateDecorations(editor.document);
  editor.setDecorations(templateInterpolationDecoration, interpolationRanges);
}

function normalizeMacroBody(body) {
  return body
    .replace(/\$`[\s\S]*?`/g, "__idsl_template__")
    .replace(/\$lisp\{[\s\S]*?\}/g, "__idsl_lisp__")
    .replace(/\$\([\s\S]*?\)\.\.\.(?:\[(?:last|-?\d+)\])?/g, "__idsl_repeat__")
    .replace(/\$([A-Za-z_$\p{L}][A-Za-z0-9_$\p{L}]*)\[(last|-?\d+)\]/gu, "__idsl_$1[0]")
    .replace(/\$([A-Za-z_$\p{L}][A-Za-z0-9_$\p{L}]*)/gu, "__idsl_$1");
}

function collectMacroBodyParams(body) {
  const params = new Set();
  const indexed = new Set();

  for (const match of body.matchAll(/\$([A-Za-z_$\p{L}][A-Za-z0-9_$\p{L}]*)/gu)) {
    params.add(`__idsl_${match[1]}`);
  }

  for (const match of body.matchAll(/\$([A-Za-z_$\p{L}][A-Za-z0-9_$\p{L}]*)\[(last|-?\d+)\]/gu)) {
    indexed.add(`__idsl_${match[1]}`);
  }

  if (/\$\([\s\S]*?\)\.\.\.(?:\[(?:last|-?\d+)\])?/u.test(body)) {
    params.add("__idsl_repeat__");
  }

  if (/\$`[\s\S]*?`/u.test(body)) {
    params.add("__idsl_template__");
  }

  if (/\$lisp\{[\s\S]*?\}/u.test(body)) {
    params.add("__idsl_lisp__");
  }

  return [...params].map(name => ({
    name,
    indexed: indexed.has(name)
  }));
}

function collectDeclaredVirtualNames(normalizedBody) {
  const names = new Set();
  const declarationRe =
    /\b(?:const|let|var|function|class)\s+(__idsl_[A-Za-z_$\p{L}][A-Za-z0-9_$\p{L}]*)/gu;

  for (const match of normalizedBody.matchAll(declarationRe)) {
    names.add(match[1]);
  }

  return names;
}

function wrapMacroBodyForLint(body) {
  const normalized = normalizeMacroBody(body);
  const declaredNames = collectDeclaredVirtualNames(normalized);
  const params = collectMacroBodyParams(body)
    .filter(param => !declaredNames.has(param.name));
  const declarations = params
    .map(param => param.indexed
      ? `const ${param.name} = [];`
      : `const ${param.name} = undefined;`)
    .join("\n");
  const prefix = declarations ? `${declarations}\n` : "";

  return {
    code: `${prefix}${normalized}`,
    lineOffset: declarations ? params.length : 0
  };
}

function extractMacroBodyRanges(text) {
  const ranges = [];
  const macroRe = /^\s*\$macro\s+([\s\S]*?)\s*#\(\s*([\s\S]*?)\s*\)#/gmd;

  for (const match of text.matchAll(macroRe)) {
    const bodyIndices = match.indices?.[2];
    if (!bodyIndices) continue;

    ranges.push({
      body: match[2],
      startOffset: bodyIndices[0],
      endOffset: bodyIndices[1]
    });
  }

  return ranges;
}

function bodyPositionToDocumentPosition(documentText, bodyStartOffset, line, column) {
  const bodyStart = offsetToPosition(documentText, bodyStartOffset);
  const targetLine = bodyStart.line + Math.max(0, line - 1);
  const targetColumn =
    line === 1
      ? bodyStart.character + Math.max(0, column - 1)
      : Math.max(0, column - 1);

  return new vscode.Position(targetLine, targetColumn);
}

async function lintMacroBodies(document, diagnostics) {
  const text = document.getText();
  const macroBodies = extractMacroBodyRanges(text);
  if (!macroBodies.length) return;

  const { ESLint } = loadWorkspaceEslint(document.uri.fsPath);
  const eslint = new ESLint({
    cwd: getWorkspaceRoot(document.uri.fsPath),
    overrideConfigFile: true,
    ignore: false,
    overrideConfig: {
      languageOptions: {
        ecmaVersion: "latest",
        sourceType: "module",
        globals: {
          console: "readonly",
          THREE: "readonly"
        }
      },
      rules: {
        "no-undef": "error",
        "no-unused-vars": ["warn", {
          args: "none",
          ignoreRestSiblings: true,
          varsIgnorePattern: "^__idsl_"
        }]
      }
    }
  });

  for (const macroBody of macroBodies) {
    const { code, lineOffset } = wrapMacroBodyForLint(macroBody.body);
    const [result] = await eslint.lintText(code, {
      filePath: `${document.uri.fsPath}.macro-body.js`
    });

    for (const message of result.messages ?? []) {
      const bodyLine = Math.max(1, (message.line ?? 1) - lineOffset);
      const bodyEndLine = Math.max(
        bodyLine,
        (message.endLine ?? message.line ?? 1) - lineOffset
      );
      const start = bodyPositionToDocumentPosition(
        text,
        macroBody.startOffset,
        bodyLine,
        message.column ?? 1
      );
      const end = bodyPositionToDocumentPosition(
        text,
        macroBody.startOffset,
        bodyEndLine,
        message.endColumn ?? (message.column ?? 1) + 1
      );

      const diagnostic = new vscode.Diagnostic(
        new vscode.Range(start, end),
        message.message,
        message.severity === 2
          ? vscode.DiagnosticSeverity.Error
          : vscode.DiagnosticSeverity.Warning
      );

      diagnostic.source = "idsl-macro-js";
      diagnostic.code = message.ruleId ?? "parse";
      diagnostics.push(diagnostic);
    }
  }
}

function activate(context) {
  const macroLintDiagnostics = vscode.languages.createDiagnosticCollection("idsl-macro-js");
  const syncShadowDebounced = debounce(async document => {
    if (!isDslDocument(document)) return;

    try {
      await syncShadowForFile(document.uri.fsPath);
    } catch (error) {
      vscode.window.showWarningMessage(`IDSL shadow sync failed: ${error.message}`);
    }
  }, 150);

  const lintMacroBodiesDebounced = debounce(async document => {
    if (!isDslDocument(document)) return;

    const diagnostics = [];

    try {
      await lintMacroBodies(document, diagnostics);
    } catch (error) {
      const fallback = new vscode.Diagnostic(
        new vscode.Range(new vscode.Position(0, 0), new vscode.Position(0, 1)),
        `Macro JS lint failed: ${error.message}`,
        vscode.DiagnosticSeverity.Warning
      );
      fallback.source = "idsl-macro-js";
      diagnostics.push(fallback);
    }

    macroLintDiagnostics.set(document.uri, diagnostics);
  }, 250);

  const refreshDecorationsDebounced = debounce(editor => {
    refreshDecorations(editor);
  }, 50);

  context.subscriptions.push(
    vscode.commands.registerCommand("idsl.syncShadow", async () => {
      const editor = vscode.window.activeTextEditor;
      if (!editor || !isDslDocument(editor.document)) {
        vscode.window.showInformationMessage("Open an .idsl/.dsljs file first.");
        return;
      }

      try {
        const shadowPath = await syncShadowForFile(editor.document.uri.fsPath);
        vscode.window.showInformationMessage(`IDSL shadow synced: ${path.basename(shadowPath)}`);
      } catch (error) {
        vscode.window.showErrorMessage(`IDSL shadow sync failed: ${error.message}`);
      }
    })
  );

  context.subscriptions.push(
    vscode.languages.registerDefinitionProvider(SELECTOR, {
      async provideDefinition(document, position) {
        const symbolInfo = getDslSymbolAtPosition(document, position);
        if (!symbolInfo) return null;

        const { symbol } = symbolInfo;
        const macroDefs = collectMacroDefinitions(document);
        if (macroDefs.has(symbol)) {
          return macroDefs.get(symbol);
        }

        const defs = collectDefinitions(document);
        if (defs.has(symbol)) {
          return defs.get(symbol);
        }

        return await provideGeneratedDefinition(document, position, symbol);
      }
    })
  );

  context.subscriptions.push(
    vscode.languages.registerHoverProvider(SELECTOR, {
      async provideHover(document, position) {
        const symbolInfo = getDslSymbolAtPosition(document, position);
        if (!symbolInfo) return null;

        const { symbol, range } = symbolInfo;
        const macroDefinitions = collectMacroDefinitions(document);
        if (macroDefinitions.has(symbol)) {
          const location = macroDefinitions.get(symbol);
          const macroDocument = location.uri.fsPath === document.uri.fsPath
            ? document
            : await vscode.workspace.openTextDocument(location.uri);
          const line = macroDocument.lineAt(location.range.start.line).text.trim();
          const markdown = new vscode.MarkdownString();
          markdown.appendCodeblock(line, "dsl");
          if (location.uri.fsPath !== document.uri.fsPath) {
            markdown.appendMarkdown(`\n\nDefined in \`${location.uri.fsPath}\``);
          }
          return new vscode.Hover(markdown, range);
        }

        const definitions = collectDefinitions(document);
        if (definitions.has(symbol)) {
          try {
            const expanded = await compileSource(document.getText(), document.uri.fsPath);
            const snippet = findGeneratedSnippet(expanded, symbol);
            if (!snippet) return null;

            const markdown = new vscode.MarkdownString();
            markdown.appendCodeblock(snippet, "javascript");
            markdown.isTrusted = true;
            return new vscode.Hover(markdown, range);
          } catch {
            return null;
          }
        }

        return await provideGeneratedHover(document, position, symbol);
      }
    })
  );

  context.subscriptions.push(
    vscode.languages.registerDocumentSemanticTokensProvider(
      SELECTOR,
      { provideDocumentSemanticTokens: provideSemanticTokens },
      legend
    )
  );

  context.subscriptions.push(
    vscode.window.onDidChangeActiveTextEditor(editor => {
      refreshDecorationsDebounced(editor);
    }),
    vscode.workspace.onDidOpenTextDocument(document => {
      syncShadowDebounced(document);
      lintMacroBodiesDebounced(document);
      if (vscode.window.activeTextEditor?.document === document) {
        refreshDecorationsDebounced(vscode.window.activeTextEditor);
      }
    }),
    vscode.workspace.onDidSaveTextDocument(document => {
      syncShadowDebounced(document);
      lintMacroBodiesDebounced(document);
      if (vscode.window.activeTextEditor?.document === document) {
        refreshDecorationsDebounced(vscode.window.activeTextEditor);
      }
    }),
    vscode.workspace.onDidChangeTextDocument(event => {
      syncShadowDebounced(event.document);
      lintMacroBodiesDebounced(event.document);
      if (vscode.window.activeTextEditor?.document === event.document) {
        refreshDecorationsDebounced(vscode.window.activeTextEditor);
      }
    })
  );

  for (const document of vscode.workspace.textDocuments) {
    syncShadowDebounced(document);
    lintMacroBodiesDebounced(document);
  }

  refreshDecorations(vscode.window.activeTextEditor);
  context.subscriptions.push(
    macroLintDiagnostics,
    macroNameDecoration,
    templateInterpolationDecoration
  );
}

function deactivate() {}

module.exports = {
  activate,
  deactivate
};
